// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface CameraResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CameraResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string activity = 1;</code>
   */
  java.lang.String getActivity();
  /**
   * <code>string activity = 1;</code>
   */
  com.google.protobuf.ByteString
      getActivityBytes();
}
