// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface CameraRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CameraRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
