// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface CameraOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Camera)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string view = 2;</code>
   */
  java.lang.String getView();
  /**
   * <code>string view = 2;</code>
   */
  com.google.protobuf.ByteString
      getViewBytes();
}
