// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface DimRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.DimRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float dimness = 1;</code>
   */
  float getDimness();
}
