// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface MotionResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.MotionResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string report = 1;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
