// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface MotionSensorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.MotionSensor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>bool power = 3;</code>
   */
  boolean getPower();

  /**
   * <code>string activity = 4;</code>
   */
  java.lang.String getActivity();
  /**
   * <code>string activity = 4;</code>
   */
  com.google.protobuf.ByteString
      getActivityBytes();

  /**
   * <code>string activity2 = 5;</code>
   */
  java.lang.String getActivity2();
  /**
   * <code>string activity2 = 5;</code>
   */
  com.google.protobuf.ByteString
      getActivity2Bytes();
}
