// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_MotionRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_MotionRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_MotionResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_MotionResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_MotionSensor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_MotionSensor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CameraRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CameraRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CameraResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CameraResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_Camera_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_Camera_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_DimRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_DimRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_DimResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_DimResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"\"\n\024MotionRequ" +
      "estMessage\022\n\n\002id\030\001 \001(\005\"\'\n\025MotionResponse" +
      "Message\022\016\n\006report\030\001 \001(\t\"`\n\014MotionSensor\022" +
      "\n\n\002id\030\001 \001(\005\022\020\n\010location\030\002 \001(\t\022\r\n\005power\030\003" +
      " \001(\010\022\020\n\010activity\030\004 \001(\t\022\021\n\tactivity2\030\005 \001(" +
      "\t\"\"\n\024CameraRequestMessage\022\n\n\002id\030\001 \001(\005\")\n" +
      "\025CameraResponseMessage\022\020\n\010activity\030\001 \001(\t" +
      "\"\"\n\006Camera\022\n\n\002id\030\001 \001(\005\022\014\n\004view\030\002 \001(\t\"$\n\021" +
      "DimRequestMessage\022\017\n\007dimness\030\001 \001(\002\"$\n\022Di" +
      "mResponseMessage\022\016\n\006result\030\001 \001(\t2\354\001\n\010Ser" +
      "vice3\022M\n\006motion\022\036.service3.MotionRequest" +
      "Message\032\037.service3.MotionResponseMessage" +
      "\"\0000\001\022K\n\006camera\022\036.service3.CameraRequestM" +
      "essage\032\037.service3.CameraResponseMessage\"" +
      "\000\022D\n\003dim\022\033.service3.DimRequestMessage\032\034." +
      "service3.DimResponseMessage\"\0000\001B\035\n\013ds.se" +
      "rvice3B\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_MotionRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_MotionRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_MotionRequestMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_service3_MotionResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_MotionResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_MotionResponseMessage_descriptor,
        new java.lang.String[] { "Report", });
    internal_static_service3_MotionSensor_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_MotionSensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_MotionSensor_descriptor,
        new java.lang.String[] { "Id", "Location", "Power", "Activity", "Activity2", });
    internal_static_service3_CameraRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_CameraRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CameraRequestMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_service3_CameraResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_CameraResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CameraResponseMessage_descriptor,
        new java.lang.String[] { "Activity", });
    internal_static_service3_Camera_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_Camera_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_Camera_descriptor,
        new java.lang.String[] { "Id", "View", });
    internal_static_service3_DimRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service3_DimRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_DimRequestMessage_descriptor,
        new java.lang.String[] { "Dimness", });
    internal_static_service3_DimResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_service3_DimResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_DimResponseMessage_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
