// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface PresetResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.PresetResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();
}
