// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_SetTemperatureRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_SetTemperatureRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_SetTemperatureResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_SetTemperatureResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidifyRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidifyRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidifyResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidifyResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_PresetRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_PresetRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_PresetResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_PresetResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Device_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\".\n\034SetTempera" +
      "tureRequestMessage\022\016\n\006degree\030\001 \001(\002\"-\n\035Se" +
      "tTemperatureResponseMessage\022\014\n\004item\030\001 \001(" +
      "\t\"&\n\026HumidifyRequestMessage\022\014\n\004item\030\001 \001(" +
      "\t\"\'\n\027HumidifyResponseMessage\022\014\n\004item\030\001 \001" +
      "(\t\"$\n\024PresetRequestMessage\022\014\n\004item\030\001 \001(\t" +
      "\"%\n\025PresetResponseMessage\022\014\n\004item\030\001 \001(\t\"" +
      "D\n\006Device\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005p" +
      "ower\030\003 \001(\010\022\021\n\tintensity\030\004 \001(\0022\233\002\n\010Servic" +
      "e2\022e\n\016setTemperature\022&.service2.SetTempe" +
      "ratureRequestMessage\032\'.service2.SetTempe" +
      "ratureResponseMessage\"\0000\001\022W\n\ndehumidify\022" +
      " .service2.HumidifyRequestMessage\032!.serv" +
      "ice2.HumidifyResponseMessage\"\000(\0010\001\022O\n\006pr" +
      "eset\022\036.service2.PresetRequestMessage\032\037.s" +
      "ervice2.PresetResponseMessage\"\000(\0010\001B\035\n\013d" +
      "s.service2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_SetTemperatureRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_SetTemperatureRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_SetTemperatureRequestMessage_descriptor,
        new java.lang.String[] { "Degree", });
    internal_static_service2_SetTemperatureResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_SetTemperatureResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_SetTemperatureResponseMessage_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_service2_HumidifyRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_HumidifyRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidifyRequestMessage_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_service2_HumidifyResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_HumidifyResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidifyResponseMessage_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_service2_PresetRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_PresetRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_PresetRequestMessage_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_service2_PresetResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_PresetResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_PresetResponseMessage_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_service2_Device_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service2_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Device_descriptor,
        new java.lang.String[] { "Id", "Name", "Power", "Intensity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
