// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface SetTemperatureRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.SetTemperatureRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float degree = 1;</code>
   */
  float getDegree();
}
