// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface CreateResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.CreateResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();
}
