// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface DeviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Device)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool power = 3;</code>
   */
  boolean getPower();

  /**
   * <code>float intensity = 4;</code>
   */
  float getIntensity();
}
