// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface InspectRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.InspectRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
