// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface ListRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ListRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1;</code>
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
